/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        "2xl": "1440px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      colors: {
        surface: {
          DEFAULT: "#0c1322",
          dim: "#0c1322",
          bright: "#323949",
          "container-lowest": "#070e1d",
          "container-low": "#141b2b",
          container: "#191f2f",
          "container-high": "#232a3a",
          "container-highest": "#2e3545",
        },
        "on-surface": "#dce2f7",
        "on-surface-variant": "#d8c3ad",
        background: "#0c1322",
        "on-background": "#dce2f7",
        primary: {
          DEFAULT: "#ffc174",
          foreground: "#472a00",
          container: "#f59e0b",
          "container-foreground": "#613b00",
          fixed: "#ffddb8",
          "fixed-dim": "#ffb95f",
        },
        "on-primary": "#472a00",
        "on-primary-container": "#613b00",
        "on-primary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#653e00",
        secondary: {
          DEFAULT: "#ffb690",
          foreground: "#552100",
          container: "#ec6a06",
          "container-foreground": "#4a1c00",
          fixed: "#ffdbca",
          "fixed-dim": "#ffb690",
        },
        "on-secondary": "#552100",
        "on-secondary-container": "#4a1c00",
        tertiary: {
          DEFAULT: "#56e5a9",
          foreground: "#003824",
          container: "#30c88f",
          "container-foreground": "#004e34",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
        },
        "on-tertiary": "#003824",
        "on-tertiary-container": "#004e34",
        error: {
          DEFAULT: "#ffb4ab",
          foreground: "#690005",
          container: "#93000a",
          "container-foreground": "#ffdad6",
        },
        outline: {
          DEFAULT: "#a08e7a",
          variant: "#534434",
        },
        border: "rgba(255, 255, 255, 0.1)",
        input: "#1e293b",
        ring: "#ffc174",
        card: {
          DEFAULT: "#191f2f",
          foreground: "#dce2f7",
        },
        popover: {
          DEFAULT: "#191f2f",
          foreground: "#dce2f7",
        },
        muted: {
          DEFAULT: "#1e293b",
          foreground: "#94a3b8",
        },
        accent: {
          DEFAULT: "#232a3a",
          foreground: "#dce2f7",
        },
        destructive: {
          DEFAULT: "#ef4444",
          foreground: "#fef2f2",
        },
      },
      borderRadius: {
        lg: "0.5rem",
        md: "0.375rem",
        sm: "0.25rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-lg": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "data-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      keyframes: {
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
